name: Hprofile CI
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Testing:
    runs-on: ubuntu-latest 
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Maven Test
        run: mvn test
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
      - name: Set Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java HelloWorldApp.java


 
