name: Hprofile CI
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: echo "workflow works!"
      - name: Build Image
        run: echo "building docker image!"
